app = "ask-ginetta-vespa-index"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
dockerfile = "Dockerfile"

[[services]]
internal_port = 19071
protocol = "tcp"

[[services.ports]]
handlers = ["http"]
port = 19071

[[services]]
internal_port = 8081
protocol = "tcp"

[[services.ports]]
handlers = ["http"]
port = 8081

[mounts]
source = "vespa_data"
destination = "/opt/vespa/var"

[experimental]
private_network = true
