# fly.toml file generated for danswer-api on Fly.io

app = "ask-ginetta-backend"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
dockerfile = "Dockerfile"

[env]
AUTH_TYPE = "disabled"
SESSION_EXPIRE_TIME_SECONDS = "86400"
# VALID_EMAIL_DOMAINS = ""
# GOOGLE_OAUTH_CLIENT_ID = ""
# GOOGLE_OAUTH_CLIENT_SECRET = ""
# REQUIRE_EMAIL_VERIFICATION = ""
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = "587"
# SMTP_USER = ""
# SMTP_PASS = ""
# EMAIL_FROM = ""

# GEN_AI_MODEL_PROVIDER = ""
# GEN_AI_MODEL_VERSION = ""
# FAST_GEN_AI_MODEL_VERSION = ""
# GEN_AI_API_KEY = ""
# GEN_AI_API_ENDPOINT = ""
# GEN_AI_API_VERSION = ""
# GEN_AI_LLM_PROVIDER_TYPE = ""
# GEN_AI_MAX_TOKENS = ""
# QA_TIMEOUT = ""
# MAX_CHUNKS_FED_TO_CHAT = ""
DISABLE_LLM_FILTER_EXTRACTION = "true"
DISABLE_LLM_CHUNK_FILTER = "true"
DISABLE_LLM_CHOOSE_SEARCH = "true"
DISABLE_LLM_QUERY_REPHRASE = "true"
DISABLE_GENERATIVE_AI = "true"
# DOC_TIME_DECAY = ""
# HYBRID_ALPHA = ""
# EDIT_KEYWORD_QUERY = ""
# MULTILINGUAL_QUERY_EXPANSION = ""
# QA_PROMPT_OVERRIDE = ""

POSTGRES_HOST = "ask-ginetta-relational-db.internal"
VESPA_HOST = "ask-ginetta-index.internal"

# WEB_DOMAIN = ""
# DOCUMENT_ENCODER_MODEL = ""
# DOC_EMBEDDING_DIM = ""
# NORMALIZE_EMBEDDINGS = "true"
# ASYM_QUERY_PREFIX = ""
ENABLE_RERANKING_REAL_TIME_FLOW = "true"
ENABLE_RERANKING_ASYNC_FLOW = "true"
# MODEL_SERVER_HOST = ""
# MODEL_SERVER_PORT = ""

DISABLE_TELEMETRY = "false"
LOG_LEVEL = "info"
LOG_ALL_MODEL_INTERACTIONS = ""
LOG_VESPA_TIMING_INFORMATION = ""

[[services]]
internal_port = 8080
protocol = "tcp"

[[services.ports]]
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[mounts]]
source = "model_storage"
destination = "/application/model_files"
